export const TOOLS = {
  no: {
    title: 'No as a Service 🚫',
    sub: 'Set boundaries with confidence',
    roulette: 'No Roulette',
    dayLbl: '✨ No of the Day ✨',
    quotes: [
      '"Saying no is a complete sentence."',
      '"No is a full sentence — it requires no justification."',
      '"Every time you say no to the wrong thing, you say yes to the right thing."',
      '"You teach people how to treat you by what you allow."',
    ],
    catTitle: 'What are you saying "No" to?',
    cats: [
      { name: 'Work Request',  desc: 'Decline extra tasks',           bg: '#f59e0b', tx: '#000' },
      { name: 'Social Event',  desc: 'Skip gatherings gracefully',    bg: '#10b981', tx: '#000' },
      { name: 'Favor',         desc: "Turn down a friend's ask",      bg: '#ec4899', tx: '#000' },
      { name: 'Meeting',       desc: 'Skip unnecessary meetings',     bg: '#0ea5e9', tx: '#000' },
      { name: 'Deadline',      desc: 'Push back on timelines',        bg: '#f97316', tx: '#000' },
      { name: 'Relationship',  desc: 'Hold personal limits firm',     bg: '#8b5cf6', tx: '#000' },
    ],
    toneTitle: 'Choose your tone',
    tones: [
      { name: 'Firm',       desc: 'Clear and direct',    emoji: '✊', bg: '#f43f5e', tx: '#000' },
      { name: 'Kind',       desc: 'Warm but clear',      emoji: '🌸', bg: '#10b981', tx: '#000' },
      { name: 'Apologetic', desc: 'Gentle and sorry',    emoji: '😔', bg: '#f43f5e', tx: '#000' },
      { name: 'Funny',      desc: 'Light-hearted no',    emoji: '😄', bg: '#f59e0b', tx: '#000' },
    ],
    recip: 'Who are you saying no to?',
    reason: 'Any specific reason? (Optional)',
    outLbl: 'Your "No" Message:',
    buildPrompt: (cat, tone, name, ctx) =>
      `Write a "${tone}" refusal for: ${cat}${name ? ` to ${name}` : ''}${ctx ? `. Context: ${ctx}` : ''}.`,
  },

  yeah: {
    title: 'Yeah as a Service ✅',
    sub: 'Say yes with intention',
    roulette: 'Yes Roulette',
    dayLbl: '✨ Yes of the Day ✨',
    quotes: [
      '"I\'d be honored to join you for this opportunity."',
      '"Yes — and I\'m excited to make it happen."',
      '"Count me in. Let\'s do this."',
      '"Absolutely. I\'d love to be part of this."',
    ],
    catTitle: 'What are you saying "Yes" to?',
    cats: [
      { name: 'Opportunity',   desc: 'Accept a new challenge',         bg: '#10b981', tx: '#000' },
      { name: 'Help Request',  desc: 'Support someone who needs help', bg: '#ec4899', tx: '#000' },
      { name: 'Social Invite', desc: 'Accept an invitation',           bg: '#0ea5e9', tx: '#000' },
      { name: 'Work Project',  desc: 'Take on a new assignment',       bg: '#f59e0b', tx: '#000' },
      { name: 'Date',          desc: 'Accept a romantic proposition',  bg: '#d946ef', tx: '#000' },
      { name: 'Collaboration', desc: 'Join a shared project or goal',  bg: '#f97316', tx: '#000' },
    ],
    toneTitle: 'Choose your tone',
    tones: [
      { name: 'Grateful',  desc: 'Thankful & appreciative', emoji: '🙏', bg: '#0ea5e9', tx: '#000' },
      { name: 'Excited',   desc: 'Enthusiastic & energetic', emoji: '🎉', bg: '#10b981', tx: '#000' },
      { name: 'Chill',     desc: 'Relaxed & easy-going',    emoji: '😎', bg: '#f59e0b', tx: '#000' },
      { name: 'Assertive', desc: 'Confident & clear',       emoji: '💪', bg: '#f97316', tx: '#000' },
    ],
    recip: 'Who are you saying yes to?',
    reason: 'Any specific reason? (Optional)',
    outLbl: 'Your "Yes" Message:',
    buildPrompt: (cat, tone, name, ctx) =>
      `Write a "${tone}" acceptance for: ${cat}${name ? ` to ${name}` : ''}${ctx ? `. Context: ${ctx}` : ''}.`,
  },

  maybe: {
    title: 'Maybe as a Service 🤷',
    sub: 'Delay decisions politely',
    roulette: 'Maybe Roulette',
    dayLbl: '✨ Maybe of the Day ✨',
    quotes: [
      '"That\'s interesting. Let me consider my options first."',
      '"I need a bit more time to think this through."',
      '"Let me circle back — I want to give it proper thought."',
      '"I\'m considering it. Can I get back to you by end of week?"',
    ],
    catTitle: 'What are you postponing?',
    cats: [
      { name: 'Meeting',  desc: 'Postpone a meeting or event',      bg: '#8b5cf6', tx: '#000' },
      { name: 'Date',     desc: 'Delay a romantic engagement',       bg: '#d946ef', tx: '#000' },
      { name: 'Project',  desc: 'Extend a project timeline',         bg: '#0ea5e9', tx: '#000' },
      { name: 'Response', desc: 'Buy time before responding',        bg: '#f59e0b', tx: '#000' },
      { name: 'Event',    desc: 'Tentatively accept an invitation',  bg: '#10b981', tx: '#000' },
      { name: 'Request',  desc: 'Delay answering a request',         bg: '#f97316', tx: '#000' },
    ],
    toneTitle: 'Pick your vibe',
    tones: [
      { name: 'Gentle',      desc: 'Soft and considerate',       emoji: '🌸', bg: '#d946ef', tx: '#000' },
      { name: 'Honest',      desc: 'Straightforward and direct', emoji: '🤝', bg: '#f59e0b', tx: '#000' },
      { name: 'Overwhelmed', desc: 'Busy and stretched thin',    emoji: '😅', bg: '#0ea5e9', tx: '#000' },
      { name: 'Playful',     desc: 'Light-hearted and humorous', emoji: '😂', bg: '#ec4899', tx: '#000' },
    ],
    recip: 'Who are you responding to?',
    reason: 'Why are you postponing this?',
    outLbl: 'Your "Maybe" message:',
    buildPrompt: (cat, tone, name, ctx) =>
      `Write a "${tone}" delay/maybe response for: ${cat}${name ? ` to ${name}` : ''}${ctx ? `. Context: ${ctx}` : ''}.`,
  },

  ghost: {
    title: 'Ghost as a Service 👻',
    sub: 'Exit conversations softly',
    roulette: 'Ghost Roulette',
    dayLbl: '✨ Ghost Quote of the Day ✨',
    quotes: [
      '"Your energy is finite. Spend it wisely."',
      '"Not every connection needs a conclusion."',
      '"Fading gracefully is still an art form."',
      '"Some doors are better left quietly closed."',
    ],
    catTitle: 'What are you ghosting?',
    cats: [
      { name: 'DM',           desc: 'Exit direct message threads',        bg: '#0ea5e9', tx: '#000' },
      { name: 'Chat Group',   desc: 'Leave a group conversation quietly',  bg: '#8b5cf6', tx: '#000' },
      { name: 'Date',         desc: 'Fade out of dating situations',       bg: '#d946ef', tx: '#000' },
      { name: 'Work Chat',    desc: 'Exit work conversations gracefully',  bg: '#10b981', tx: '#000' },
      { name: 'Acquaintance', desc: 'Distance from casual connections',    bg: '#f59e0b', tx: '#000' },
      { name: 'Client',       desc: 'Wind down client communications',     bg: '#ec4899', tx: '#000' },
    ],
    toneTitle: 'Choose your tone',
    tones: [
      { name: 'Graceful',     desc: 'Soft and considerate',  emoji: '🦢', bg: '#10b981', tx: '#000' },
      { name: 'Honest',       desc: 'Direct but kind',       emoji: '✨', bg: '#8b5cf6', tx: '#000' },
      { name: 'Mysterious',   desc: 'Vague and enigmatic',   emoji: '🔮', bg: '#d946ef', tx: '#000' },
      { name: 'Excuse-based', desc: 'Plausible explanations',emoji: '😬', bg: '#ec4899', tx: '#000' },
    ],
    recip: 'Who are you ghosting?',
    reason: 'Why are you exiting this conversation?',
    outLbl: 'Your "Ghost" Message:',
    buildPrompt: (cat, tone, name, ctx) =>
      `Write a "${tone}" exit message for ghosting: ${cat}${name ? ` (person: ${name})` : ''}${ctx ? `. Reason: ${ctx}` : ''}.`,
  },

  permission: {
    title: 'Permission Slip Generator 📄',
    sub: 'Give yourself permission to be human',
    roulette: 'Random Slip',
    dayLbl: '✨ Slip of the Day ✨',
    quotes: [
      '"Perfect is the enemy of done. You are doing enough."',
      '"You have permission to rest. You are not a machine."',
      '"Giving yourself grace is not weakness — it\'s wisdom."',
      '"You don\'t need to earn your rest."',
    ],
    catTitle: 'What do you need permission for?',
    cats: [
      { name: 'Rest',              desc: 'Pause and recharge',             bg: '#10b981', tx: '#000' },
      { name: 'Saying No',         desc: 'Set boundaries without guilt',   bg: '#8b5cf6', tx: '#000' },
      { name: 'Being Imperfect',   desc: 'Embrace your human nature',      bg: '#f59e0b', tx: '#000' },
      { name: 'Not Replying',      desc: 'Take space from digital life',   bg: '#0ea5e9', tx: '#000' },
      { name: 'Time Alone',        desc: 'Honor your need for solitude',   bg: '#ec4899', tx: '#000' },
      { name: 'Setting Boundaries',desc: 'Protect your energy',            bg: '#f97316', tx: '#000' },
    ],
    toneTitle: 'Choose your tone',
    tones: [
      { name: 'Gentle',     desc: 'Soft and nurturing',       emoji: '🌸', bg: '#d946ef', tx: '#000' },
      { name: 'Empowering', desc: 'Bold and affirming',       emoji: '✨', bg: '#8b5cf6', tx: '#000' },
      { name: 'Clinical',   desc: 'Research-backed rational', emoji: '📋', bg: '#10b981', tx: '#000' },
      { name: 'Cheerful',   desc: 'Uplifting and positive',   emoji: '😊', bg: '#f59e0b', tx: '#000' },
    ],
    recip: 'Who is this permission slip for?',
    reason: null,
    outLbl: 'Your Permission Slip:',
    isSlip: true,
    buildPrompt: (cat, tone, name) =>
      `Write a "${tone}" self-permission statement for: ${cat}${name ? ` for ${name}` : ''}. 2-3 affirming sentences.`,
  },

  boundary: {
    title: 'Boundary Bot 🔔',
    sub: 'Your personal boundary coach',
    dayLbl: '✨ Reminder of the Day ✨',
    quotes: [
      '"You cannot pour from an empty cup. Fill yours first."',
      '"Boundaries are a form of self-respect."',
      '"It\'s okay to protect your peace."',
      '"Your needs matter just as much as anyone else\'s."',
    ],
    catTitle: 'What kind of boundary?',
    cats: [
      { name: 'Work',      desc: 'Professional boundaries', bg: '#0ea5e9', tx: '#000' },
      { name: 'Social',    desc: 'Friend & social circles', bg: '#10b981', tx: '#000' },
      { name: 'Family',    desc: 'Family relationships',    bg: '#f59e0b', tx: '#000' },
      { name: 'Messages',  desc: 'Digital communication',   bg: '#ec4899', tx: '#000' },
      { name: 'Self-talk', desc: 'Internal boundaries',     bg: '#8b5cf6', tx: '#000' },
    ],
    toneTitle: 'Choose your reminder tone',
    tones: [
      { name: 'Encouraging', desc: 'Supportive & positive',      emoji: '⭐', bg: '#f59e0b', tx: '#000' },
      { name: 'Firm',        desc: 'Clear and direct',           emoji: '✋', bg: '#f43f5e', tx: '#000' },
      { name: 'Reflective',  desc: 'Thoughtful & introspective', emoji: '🤔', bg: '#8b5cf6', tx: '#000' },
      { name: 'Funny',       desc: 'Light-hearted & humorous',   emoji: '😂', bg: '#ec4899', tx: '#000' },
    ],
    recip: 'Who are you setting boundaries with?',
    reason: 'Describe the specific boundary situation',
    outLbl: 'Your Boundary Reminder:',
    buildPrompt: (cat, tone, name, ctx) =>
      `Write a "${tone}" boundary reminder for: ${cat} boundaries${name ? ` with ${name}` : ''}${ctx ? `. Situation: ${ctx}` : ''}.`,
  },
}

export const ALL_TILES = [
  { id: 'no',         emoji: '🚫', name: 'No as a Service',       desc: 'Set boundaries with confidence'        },
  { id: 'yeah',       emoji: '✅', name: 'Yeah as a Service',      desc: 'Say yes with intention'                },
  { id: 'maybe',      emoji: '🤷', name: 'Maybe as a Service',     desc: 'Delay decisions politely'              },
  { id: 'ghost',      emoji: '👻', name: 'Ghost as a Service',     desc: 'Exit conversations softly'             },
  { id: 'boundary',   emoji: '🔔', name: 'Boundary Bot',           desc: 'Your personal boundary coach'          },
  { id: 'permission', emoji: '📄', name: 'Permission Slip',        desc: 'Give yourself permission to be human'  },
]

export const NAV = [
  { id: 'no',         icon: '🚫', label: 'No as a Service'   },
  { id: 'yeah',       icon: '✅', label: 'Yeah as a Service'  },
  { id: 'maybe',      icon: '🤷', label: 'Maybe as a Service' },
  { id: 'ghost',      icon: '👻', label: 'Ghost as a Service' },
  { id: 'boundary',   icon: '🔔', label: 'Boundary Bot'       },
  { id: 'permission', icon: '📄', label: 'Permission Slip'    },
]
